name: Deploy DBML docs to GitHub Pages

on:
  pull_request:
    branches:
      - main
    paths:
      - 'page-docs/**'
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

# defaults:
#   run:
#     working-directory: page-docs

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-22.04

    steps:
      - name: Log path
        run: pwd
        working-directory: page-docs
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        working-directory: page-docs
        run: yarn install --frozen-lockfile
      - name: Build website
        working-directory: page-docs
        run: yarn build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build
